<?php
use Drupal\node\Entity\Node;
/**
*Adding the hook cron function
*
**/

function drupal_cron_cron() {
	//echo "Shubham";
	$slogan = \Drupal::service('config.factory')->getEditable('system.site')->get('slogan');
	if (is_numeric($slogan)){
		$slogan = $slogan+1;
		\Drupal::service('config.factory')->getEditable('system.site')->set(
			'slogan',$slogan)-> save();
	}
	else
	{
		\Drupal::service('config.factory')->getEditable('system.site')->set(
			'slogan',0)-> save();
	}
	$data = file_get_contents('http://delivery.chalk247.com/team_list/NFL.JSON?api_key=74db8efa2a6db279393b433d97c2bc843f8e32b0');
  	$cat_facts = json_decode($data, TRUE);
 /* 
  foreach ($cat_facts as $cat_fact) {
    //$number = range(0,count($cat_fact));
    //print $cat_fact;*/
    print_r($cat_fact[data][team][0]);
  
  
	$node = Node::create(['type' => 'team']);
	 $node->set('title','Testing1111');
	 $node->set('field_id',$cat_fact[data][team][0][id]);
	 $node->set('field_name',$cat_fact[data][team][0][name]);
	 $node->set('field_nickname',$cat_fact[data][team][0][nickname]);
	 $node->set('field_display_name',$cat_fact[data][team][0][display_name]);
	 $node->set('field_division',$cat_fact[data][team][0][division]);
	 $node->set('field_conference',$cat_fact[data][team][0][conference]);
	 $node->status = 1;
	 $node->save();
	//}
	

}							